apiVersion: v1
kind: Service
metadata:
  name: peliculaapi-service
spec:
  type: NodePort
  selector:
    app: peliculaapi
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
    nodePort: 30007