version: '3'
services:
  web:
    build: 
      context: .
      dockerfile: Dockerfile  # Si tienes un Dockerfile personalizado, especifícalo aquí
    ports:
      - "8080:80"
    volumes:
      - .:/app
      - /app/node_modules
