USE [master]
GO
/****** Object:  Database [LukyTV]    Script Date: 17/08/2024 09:31:23 p. m. ******/
CREATE DATABASE [LukyTV]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'LukyTV', FILENAME = N'C:\ProgramData\SOLIDWORKS Electrical\MSSQL15.TEW_SQLEXPRESS\MSSQL\DATA\LukyTV.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'LukyTV_log', FILENAME = N'C:\ProgramData\SOLIDWORKS Electrical\MSSQL15.TEW_SQLEXPRESS\MSSQL\DATA\LukyTV_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO
ALTER DATABASE [LukyTV] SET COMPATIBILITY_LEVEL = 150
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [LukyTV].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [LukyTV] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [LukyTV] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [LukyTV] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [LukyTV] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [LukyTV] SET ARITHABORT OFF 
GO
ALTER DATABASE [LukyTV] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [LukyTV] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [LukyTV] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [LukyTV] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [LukyTV] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [LukyTV] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [LukyTV] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [LukyTV] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [LukyTV] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [LukyTV] SET  DISABLE_BROKER 
GO
ALTER DATABASE [LukyTV] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [LukyTV] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [LukyTV] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [LukyTV] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [LukyTV] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [LukyTV] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [LukyTV] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [LukyTV] SET RECOVERY SIMPLE 
GO
ALTER DATABASE [LukyTV] SET  MULTI_USER 
GO
ALTER DATABASE [LukyTV] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [LukyTV] SET DB_CHAINING OFF 
GO
ALTER DATABASE [LukyTV] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [LukyTV] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [LukyTV] SET DELAYED_DURABILITY = DISABLED 
GO
ALTER DATABASE [LukyTV] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO
ALTER DATABASE [LukyTV] SET QUERY_STORE = OFF
GO
USE [LukyTV]
GO

/****** Object:  Table [dbo].[Genres]    Script Date: 17/08/2024 09:31:24 p. m. ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Genres](
	[GenreId] [int] IDENTITY(1,1) NOT NULL,
	[genreName] [varchar](50) NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[GenreId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY],
UNIQUE NONCLUSTERED 
(
	[genreName] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

/****** Object:  Table [dbo].[Movies]    Script Date: 17/08/2024 09:31:24 p. m. ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Movies](
	[MovieID] [int] IDENTITY(1,1) NOT NULL,
	[title] [nvarchar](255) NOT NULL,
	[releaseYear] [int] NULL,
	[GenreId] [int] NOT NULL,  -- Se añade la columna GenreId
	[poster] [varbinary](max) NULL,
	[descrip] [text] NULL,
PRIMARY KEY CLUSTERED 
(
	[MovieID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO

ALTER TABLE dbo.Movies
ADD CONSTRAINT FK_Movies_Genres
FOREIGN KEY (GenreId)
REFERENCES dbo.Genres(GenreId);

/****** Object:  Table [dbo].[usuarios]    Script Date: 17/08/2024 09:31:24 p. m. ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[usuarios](
	[UserId] [int] IDENTITY(1,1) NOT NULL,
	[userName] [varchar](50) NOT NULL,
	[userEmail] [varchar](100) NOT NULL,
	[userPassword] [varchar](255) NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[UserId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY],
UNIQUE NONCLUSTERED 
(
	[userEmail] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[Movies]  WITH CHECK ADD FOREIGN KEY([genre_name])
REFERENCES [dbo].[Genres] ([genreName])
GO
USE [master]
GO
ALTER DATABASE [LukyTV] SET  READ_WRITE 
GO

